const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto'),{createApp}=require('../server');
(async()=>{const app=createApp({dbPath:':memory:',teacherKey:'test-key'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`,browser=await chromium.launch({headless:true}),original=crypto.randomInt;
async function api(c,url,data,status=200){const r=await c.request.post(base+'/api'+url,{data});assert.equal(r.status(),status,await r.text());return r.json();}async function get(c,url){const r=await c.request.get(base+'/api'+url);assert.equal(r.status(),200);return r.json();}
try{const contexts=[];for(let i=0;i<6;i++){const c=await browser.newContext();contexts.push(c);await api(c,'/register',{name:i?'Owner '+i:'Teacher',username:'alliances'+i,password:'test-password',teacherLogin:i===0,teacherKey:'test-key'});}const [h,a,b,c,d,e]=contexts;let g=await api(h,'/games',{name:'Alliance lab'}),url='/games/'+g.code;assert.equal(g.sabotageMode,'sales');const ids=[];for(const ctx of [a,b,c,d,e])ids.push((await api(ctx,url+'/join',{restaurant:'Fry Society'})).player.userId);
const ap=await a.newPage(),bp=await b.newPage(),ep=await e.newPage(),tp=await h.newPage(),errors=[];for(const p of [ap,bp,ep,tp]){p.on('pageerror',x=>errors.push(x.message));await p.goto(base);await p.locator('[data-open]').click();await p.locator(p===tp?'details[data-fold$=":teacher-settings"] > summary':'details[data-fold$=":optional"] > summary').click();}
await ap.locator('#alliance-invite-form [name=target]').selectOption(ids[1]);await ap.locator('#alliance-invite-form button').click();await bp.locator('[data-alliance-action=allianceAccept]').click();await ap.getByRole('heading',{name:'Your alliance · 2 / 4'}).waitFor();for(const [ctx,id] of [[c,ids[2]],[d,ids[3]]]){g=await api(a,url+'/allianceInvite',{target:id});const invite=(await get(ctx,url)).alliances.invitations.find(x=>x.to===id);await api(ctx,url+'/allianceAccept',{id:invite.id});}await api(a,url+'/allianceInvite',{target:ids[4]},400);g=await get(h,url);await api(a,url+'/sabotageMode',{mode:'repair',version:g.version},400);await api(a,url+'/allianceDissolve',{id:g.alliances.groups[0].id,version:g.version},400);
function seed(fn){const stored=JSON.parse(app.db.prepare('SELECT data FROM games WHERE code=?').get(g.code).data);fn(stored);stored.version++;app.db.prepare('UPDATE games SET data=? WHERE code=?').run(JSON.stringify(stored),g.code);}
seed(stored=>{stored.round=2;stored.phase='planning';for(const p of Object.values(stored.players)){p.reports=[{round:1,revenue:120000,profit:100000,units:0,items:[]}];p.menu=[{id:'1',price:480,markup:100,stock:40,addedRound:2}];}});
await ap.locator('#sabotage-form').waitFor();await ap.locator('#sabotage-form [name=target]').selectOption(ids[1]);await ap.locator('#sabotage-form [name=cost]').selectOption('3000');crypto.randomInt=()=>0;await ap.locator('#sabotage-form button').click();await ap.locator('#sabotage-dialog button:not([disabled])').waitFor();crypto.randomInt=original;assert.match(await ap.locator('.spin-result').innerText(),/25%/);await bp.locator('#sabotage-dialog').waitFor();assert.match(await bp.locator('.spin-result').innerText(),/outside rival/);assert.doesNotMatch(await bp.locator('.spin-result').innerText(),/Owner 1/);const before=await get(b,url);assert.equal(before.sabotageLedger,undefined);for(const key of ['attackerId','attacker','rate','backstab','allianceSize'])assert.equal(before.player.sabotageInbox[0][key],undefined);assert.deepEqual((await get(e,url)).player.sabotageInbox,[]);
fs.mkdirSync('output/alliances',{recursive:true});await bp.screenshot({path:'output/alliances/anonymous.png'});await bp.locator('#sabotage-dialog button').click();await ap.locator('#sabotage-dialog button').click();
crypto.randomInt=()=>9999;await api(a,url+'/sabotage',{target:ids[2],cost:1000});crypto.randomInt=original;await ep.locator('#sabotage-dialog').waitFor();assert.match(await ep.locator('.spin-result').innerText(),/Owner 1.*backstabber/);for(const ctx of [a,b,c,d,e])assert.ok((await get(ctx,url)).player.sabotageInbox.some(x=>x.exposure&&x.attacker==='Owner 1'));
await ep.setViewportSize({width:390,height:844});await ep.screenshot({path:'output/alliances/exposed-mobile.png'});assert.ok(await ep.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await tp.reload();await tp.locator('[data-open]').click();await tp.locator('details[data-fold$=":teacher-settings"] > summary').click();await tp.locator('[data-sabotage-mode]').click();await tp.locator('[data-sabotage-mode=sales]').waitFor();g=await get(h,url);assert.equal(g.sabotageMode,'repair');assert.equal(g.sabotageLedger[0].rate,25);await tp.getByRole('heading',{name:'Alliances & sabotage rules'}).scrollIntoViewIfNeeded();await tp.screenshot({path:'output/alliances/teacher.png'});
for(const ctx of [a,b,c,d,e])await api(ctx,url+'/ready',{});g=await get(h,url);g=await api(h,url+'/run',{version:g.version});assert.equal(g.sabotageLedger[0].settled,false);g=await api(h,url+'/next',{version:g.version});seed(stored=>{for(const p of Object.values(stored.players)){p.menu.push({id:'2',price:240,markup:100,stock:40,addedRound:3});p.ready=true;}});g=await get(h,url);g=await api(h,url+'/run',{version:g.version});assert.equal(g.sabotageLedger[0].settled,true);const ar=(await get(a,url)).player.reports.at(-1),br=(await get(b,url)).player.reports.at(-1);assert.equal(ar.sabotageIncome,Math.round(br.revenue*.25));assert.equal(br.sabotageStolen,ar.sabotageIncome);assert.equal(ar.profit,ar.revenue-ar.cost-ar.fees-ar.penalty);g=await api(h,url+'/reset',{version:g.version,confirmCode:g.code});assert.equal(g.alliances.groups.length,0);assert.equal(g.sabotageLedger.length,0);assert.deepEqual((await get(a,url)).player.sabotageInbox,[]);assert.deepEqual(errors,[]);console.log('PASS: four-player consent/cap, private success, class-wide exposure, teacher toggle/auth, frozen next-round payout, receipts, reset and mobile');}finally{crypto.randomInt=original;await browser.close();await new Promise(r=>app.server.close(r));app.db.close();}})().catch(e=>{console.error(e);process.exitCode=1});
