const {test}=require('node:test'),assert=require('node:assert/strict');
const alliances=require('../lib/alliances'),sabotage=require('../lib/sabotage'),{newPlayer,simulate}=require('../lib/game'),{initializeLesson}=require('../lib/lessons'),{sum}=require('../lib/achievements');
function setup(lesson='cost-markup-v1'){const g=initializeLesson({round:2,phase:'planning',penalty:500,players:{},sabotageMode:'sales'},lesson);for(const id of ['a','b','c','d','e']){const p=g.players[id]=newPlayer({id,name:id,badges:[]},id,'🍔','#123456');p.reports=[{round:1,profit:50000,revenue:60000,units:0,items:[]}];p.menu=[{id:'1',price:480,stock:40,markup:100,addedRound:1}];}return g;}
function invite(g,from,to){alliances.act(g,g.players[from],'allianceInvite',{target:to});const i=g.allianceInvites.find(i=>i.from===from&&i.to===to);alliances.act(g,g.players[to],'allianceAccept',{id:i.id});}
test('alliances require consent, cap at four, protect invites, and allow leaving',()=>{const g=setup();alliances.act(g,g.players.a,'allianceInvite',{target:'b'});assert.equal(alliances.group(g,'b'),undefined);assert.equal(alliances.view(g,'c',false).invitations.length,0);assert.throws(()=>alliances.act(g,g.players.c,'allianceAccept',{id:g.allianceInvites[0].id}));alliances.act(g,g.players.b,'allianceAccept',{id:g.allianceInvites[0].id});invite(g,'a','c');invite(g,'b','d');assert.equal(alliances.group(g,'a').members.length,4);assert.throws(()=>invite(g,'a','e'));g.players.b.ready=true;assert.throws(()=>alliances.act(g,g.players.a,'allianceLeave',{}));g.players.b.ready=false;alliances.act(g,g.players.d,'allianceLeave',{});assert.equal(alliances.group(g,'a').members.length,3);g.bonusSettings={alliances:false};assert.equal(alliances.saving(g,g.players.a,10000),0);assert.throws(()=>alliances.act(g,g.players.a,'allianceInvite',{target:'e'}));});
test('race for final slot is revalidated and old invitations cannot move between alliances',()=>{const g=setup();invite(g,'a','b');invite(g,'a','c');for(const target of ['d','e'])alliances.act(g,g.players.a,'allianceInvite',{target});const [d,e]=g.allianceInvites;alliances.act(g,g.players.d,'allianceAccept',{id:d.id});assert.throws(()=>alliances.act(g,g.players.e,'allianceAccept',{id:e.id}));alliances.dissolve(g,alliances.group(g,'a').id);assert.equal(g.allianceInvites.length,0);});
test('backstab rates snapshot alliance size, hide identity, and broadcast failure',()=>{for(const size of [2,3,4]){const g=setup();for(const id of ['b','c','d'].slice(0,size-1))invite(g,'a',id);const result=sabotage.spin(g,g.players.a,{target:'b',cost:1000},()=>0);assert.equal(result.rate,5+5*size);assert.equal(result.backstab,true);for(const id of ['b','c','d'].slice(0,size-1)){const n=sabotage.inbox(g.players[id])[0];for(const key of ['attacker','attackerId','restaurant','backstab','allianceSize','rate','roll','cost'])assert.equal(n[key],undefined);assert.equal(n.outside,true);}alliances.act(g,g.players.a,'allianceLeave',{});assert.equal(g.sabotageClaims[0].rate,5+5*size);sabotage.spin(g,g.players.a,{target:'e',cost:1000},()=>9999);for(const p of Object.values(g.players))assert.ok(p.sabotageInbox.some(n=>n.exposure&&n.attackerId==='a'));}});
test('failed first backstab notifies everyone without creating a theft',()=>{const g=setup();invite(g,'a','b');sabotage.spin(g,g.players.a,{target:'b',cost:1000},()=>9999);assert.equal(g.sabotageClaims,undefined);for(const p of Object.values(g.players))assert.ok(p.sabotageInbox.some(n=>n.exposure));assert.throws(()=>sabotage.spin(g,g.players.a,{target:'c',cost:1000},()=>0));});
for(const lesson of ['cost-markup-v1','supply-demand-v1'])test('next-round sales transfer once, conserve money, preserve savings and survive mode switches: '+lesson,()=>{const g=setup(lesson);invite(g,'a','b');const event=sabotage.spin(g,g.players.a,{target:'b',cost:1000},()=>0);assert.equal(event.rate,15);assert.equal(sum(g.players.a),49000);assert.equal(sum(g.players.b),50000);for(const p of Object.values(g.players))p.ready=true;simulate(g,()=>[]);assert.equal(g.sabotageClaims[0].settled,false);assert.ok(g.players.a.reports.at(-1).allianceSavings>0);g.round=3;g.phase='planning';g.sabotageMode='repair';g.bonusSettings={alliances:false};const base=structuredClone(g);base.sabotageClaims=[];for(const x of [g,base])simulate(x,()=>[]);const stolen=Math.round(g.players.b.reports.at(-1).revenue*.15);assert.equal(sum(g.players.a)-sum(base.players.a),stolen);assert.equal(sum(base.players.b)-sum(g.players.b),stolen);assert.equal(g.players.a.reports.at(-1).sabotageIncome,stolen);assert.equal(g.players.b.reports.at(-1).sabotageStolen,stolen);const total=Object.values(g.players).reduce((n,p)=>n+sum(p),0);sabotage.settle(g);assert.equal(Object.values(g.players).reduce((n,p)=>n+sum(p),0),total);for(const p of Object.values(g.players)){const r=p.reports.at(-1);assert.equal(r.profit,r.revenue-r.cost-r.fees-r.penalty);}});
test('skipped targets yield zero; final round sales attempts are forbidden but repair works',()=>{const g=setup();sabotage.spin(g,g.players.a,{target:'b',cost:1000},()=>0);g.round=3;g.players.b.skippedRound=3;for(const p of Object.values(g.players))p.ready=true;simulate(g,()=>[]);assert.equal(g.sabotageClaims[0].amount,0);g.round=10;g.phase='planning';g.players.a.ready=false;assert.throws(()=>sabotage.spin(g,g.players.a,{target:'c',cost:1000},()=>0));g.sabotageMode='repair';assert.equal(sabotage.spin(g,g.players.a,{target:'c',cost:1000},()=>0).damage,4000);});
test('alliance notices do not consume target slots or award victim badges',()=>{const g=setup();invite(g,'b','c');sabotage.spin(g,g.players.a,{target:'b',cost:1000},()=>0);assert.ok(g.players.c.sabotageInbox[0].allianceNotice);require('../lib/achievements').evaluateBonus(g.players.c);assert.equal(g.players.c.badges.includes(70),false);const next=sabotage.spin(g,g.players.d,{target:'c',cost:1000},()=>0);assert.equal(next.rate,10);assert.equal(g.sabotageClaims.length,2);});
