const {test}=require('node:test'),assert=require('node:assert/strict');
const {badges,evaluateBonus}=require('../lib/achievements');
test('all twenty bonus badges unlock only from matching events and never duplicate',()=>{
 const p={badges:[]};evaluateBonus(p);assert.deepEqual(p.badges,[]);
 p.mysteryBoxes=[{price:500,kind:'reward',net:500}];evaluateBonus(p);assert.deepEqual(p.badges,[51,52,55]);
 p.mysteryBoxes.push({vendor:'Vinnie',price:30000,kind:'mishap',net:-7000},{price:500,kind:'nothing',net:-500});evaluateBonus(p);assert.ok(!p.badges.includes(60));
 p.mysteryBoxes.push({vendor:'Vinnie',price:30000,kind:'reward',net:5000});
 p.sabotageHistory=[{id:'a',round:2,cost:1000,success:true},{id:'b',round:3,cost:2000,success:true},{id:'c',round:4,cost:3000,success:false},{id:'d',round:5,cost:2000,success:true}];p.sabotageSpin=p.sabotageHistory[3];p.sabotageInbox=[{success:true},{success:false}];evaluateBonus(p);assert.deepEqual(p.badges.sort((a,b)=>a-b),Array.from({length:20},(_,i)=>51+i));evaluateBonus(p);assert.equal(p.badges.length,20);assert.ok(badges.every(b=>b.icon));
});
test('legacy last spin is counted once and does not fabricate history',()=>{const p={badges:[],sabotageSpin:{id:'x',round:3,cost:1000,success:true}};evaluateBonus(p);assert.deepEqual(p.badges,[61,62,64]);p.sabotageHistory=[p.sabotageSpin];evaluateBonus(p);assert.equal(p.badges.includes(67),false);assert.equal(p.badges.includes(68),false);});
test('existing saved events backfill once without changing profits',()=>{const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{createApp}=require('../server');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'badge-migration-')),dbPath=path.join(dir,'game.db');let app=createApp({dbPath});try{app.db.prepare('INSERT INTO users(id,username,name,hash,salt) VALUES(?,?,?,?,?)').run('a','owner','Owner','unused','unused');const game={code:'ABC123',version:1,players:{a:{userId:'a',badges:[],reports:[{round:1,profit:12345}],mysteryBoxes:[{round:2,price:500,net:500,amount:1000,kind:'reward'}],sabotageSpin:{id:'old',round:2,cost:1000,success:true}}}};app.db.prepare('INSERT INTO games(code,data) VALUES(?,?)').run(game.code,JSON.stringify(game));app.db.close();app=createApp({dbPath});const user=app.db.prepare('SELECT badges FROM users WHERE id=?').get('a');assert.deepEqual(JSON.parse(user.badges),[51,52,55,61,62,64]);const saved=JSON.parse(app.db.prepare('SELECT data FROM games').get().data);assert.equal(saved.players.a.reports[0].profit,12345);assert.equal(saved.version,2);app.db.close();app=createApp({dbPath});assert.equal(JSON.parse(app.db.prepare('SELECT data FROM games').get().data).version,2);}finally{app.db.close();fs.rmSync(dir,{recursive:true,force:true});}});
