const {test}=require('node:test'),assert=require('node:assert/strict');
const lesson=require('../lib/lessons/competition'),{initializeLesson,lessonFor}=require('../lib/lessons'),{newPlayer,simulate,pricing}=require('../lib/game');
function setup(round=3,enabled=true,id='supply-demand-v1'){const p=newPlayer({id:'a',name:'A',badges:[]},'A','🍔','#123456');p.menu=[{id:'1',price:480,stock:100,markup:100,addedRound:round}];p.marketStrategies=[{round,clue:'demand',demand:'hold',price:'hold',stock:'hold'}];return [initializeLesson({round,phase:'planning',players:{a:p},competitionEnabled:enabled,penalty:500},id),p];}
function body(g,strategy='hold',good=true){return {answers:lesson.scenarios[g.round-1].cases.map(([id,name,text,type])=>({id,type:good?type:type==='direct'?'indirect':'direct',reason:good?(type==='direct'?'similar':'alternative'):'nearby'})),strategy,strategyReason:good?lesson.strategies.find(x=>x.id===strategy).reason:'guarantee'};}
test('progression, contextual classification, feedback and first-answer counts',()=>{const [g,p]=setup();for(let round=1;round<=10;round++){g.round=round;const brief=lesson.briefing(g);assert.equal(brief.cases.length,round>=6?2:1);assert.equal(brief.strategies.length,round>=3?4:0);assert.equal(brief.cases[0].type,undefined);assert.equal(brief.cases[0].explanation,undefined);assert.ok(lesson.readyError(g,p));const r=lesson.choose(g,p,body(g,'hold',round%2===0));assert.equal(lesson.readyError(g,p),null);assert.ok(r.answers.every(x=>x.explanation));assert.throws(()=>lesson.choose(g,p,body(g)));}const totals=lesson.summary(p,10).total;assert.equal(totals.classificationTotal,15);assert.equal(totals.reasonTotal,15);assert.equal(totals.strategyReasonTotal,8);assert.equal(totals.classificationRight,8);assert.equal(totals.reasonRight,8);assert.equal(totals.strategyReasonRight,4);assert.equal(lesson.scenarios[6].cases[0][3],'direct');assert.equal(lesson.scenarios[1].cases[0][3],'indirect');assert.deepEqual(p.wrongRounds,[]);assert.equal(p.mathChecksByRound,undefined);});
test('invalid, closed, skipped, disabled and math lesson requests cannot write answers',()=>{for(const edit of [(g,p)=>g.phase='results',(g,p)=>g.paused=true,(g,p)=>p.ready=true,(g,p)=>p.skippedRound=g.round,(g,p)=>g.competitionEnabled=false]){const [g,p]=setup();edit(g,p);assert.throws(()=>lesson.choose(g,p,body(g)));assert.equal(p.competitionResponses,undefined);}const [g,p]=setup();for(const b of [{},{answers:[]},{...body(g),strategy:'invented'},{...body(g),strategyReason:'invented'},{...body(g),answers:[{id:'bargain',type:'invented',reason:'similar'}]}])assert.throws(()=>lesson.choose(g,p,b));const [m,o]=setup(3,true,'cost-markup-v1');assert.equal(lesson.briefing(m),null);assert.throws(()=>lesson.choose(m,o,body(m)));assert.deepEqual(lesson.effects(m,o),{demand:1,cost:1,fee:0});});
test('wrong answers still permit submission and never affect money independently of strategy',()=>{const [g,p]=setup(),[good,q]=setup();assert.ok(lessonFor(g).readyError(g,p));lesson.choose(g,p,body(g,'value',false));lesson.choose(good,q,body(good,'value',true));assert.equal(lessonFor(g).readyError(g,p),null);p.ready=q.ready=true;simulate(g,()=>[]);simulate(good,()=>[]);const a=p.reports[0],b=q.reports[0];assert.equal(a.profit,b.profit);assert.equal(a.penalty,0);assert.equal(a.competitionFee,800);assert.equal(a.competition.strategyReasonCorrect,false);assert.equal(a.profit,a.revenue-a.cost-a.fees);});
test('response effects apply once with stock limits; off mode and introductory rounds preserve simulation',()=>{for(let round=1;round<=10;round++)for(const strategy of ['value','differentiate','convenience','hold']){const [g,p]=setup(round),[base,q]=setup(round,false);lesson.choose(g,p,body(g,strategy));const fx=lesson.effects(g,p);const item=lessonFor(g).simulateItem(g,p,p.menu[0],[p]),normal=lessonFor(base).simulateItem(base,q,q.menu[0],[q]);assert.ok(item.units<=item.stock);if(round<3)assert.deepEqual(item,normal);if(round>=3&&strategy==='differentiate')assert.ok(item.cost>normal.cost);p.menu.push({id:'2',price:300,stock:20,markup:100,addedRound:1});p.ready=true;simulate(g,()=>[]);assert.equal(p.reports[0].competitionFee,fx.fee);assert.equal(p.reports[0].fees,fx.fee);const snapshot=JSON.parse(JSON.stringify(p.reports[0].competition));g.competitionEnabled=false;assert.deepEqual(p.reports[0].competition,snapshot);assert.deepEqual(lesson.effects(g,p),{demand:1,cost:1,fee:0});}});
test('skipped rounds incur no response fee and existing alliances and sales theft still settle',()=>{const [g,p]=setup(3);const q=g.players.b=newPlayer({id:'b',name:'B',badges:[]},'B','🍟','#123456');q.menu=structuredClone(p.menu);q.ready=true;lesson.choose(g,p,body(g,'convenience'));p.skippedRound=3;g.sabotageClaims=[{id:'x',attackerId:'a',targetId:'b',round:3,rate:10,settled:false}];simulate(g,()=>[]);assert.equal(p.reports[0].competitionFee,undefined);assert.equal(p.reports[0].profit,Math.round(q.reports[0].revenue*.1));});
