const {test}=require('node:test'),assert=require('node:assert/strict');
const flash=require('../lib/flash-challenges'),{newPlayer,simulate}=require('../lib/game'),{initializeLesson}=require('../lib/lessons'),{sum}=require('../lib/achievements');
function setup(lesson='cost-markup-v1'){const g=initializeLesson({round:1,phase:'planning',players:{},penalty:500},lesson);for(const id of ['a','b','c','d','e']){const p=g.players[id]=newPlayer({id,name:id,badges:[]},id,'🍔','#123456');p.menu=[{id:'1',price:480,stock:40,markup:100,addedRound:1}];p.ready=true;}return g;}
const payload={question:'What is 2 + 2?',options:['1','2','3','4'],correct:3,seconds:30,prizes:[5000,3000,1000]};
test('countdown, privacy, one attempt, first-three ordering, retries and expiry',()=>{const g=setup(),c=flash.start(g,payload,1000);assert.throws(()=>flash.start(g,payload,1001));assert.throws(()=>flash.answer(g,g.players.a,{id:c.id,choice:3},5999));const v=flash.view(g,'a',false,6000);assert.equal(v.correct,undefined);assert.equal(v.answers,undefined);flash.answer(g,g.players.a,{id:c.id,choice:0},6000);flash.answer(g,g.players.a,{id:c.id,choice:3},6001);assert.equal(c.answers.a.correct,false);for(const id of ['b','c','d'])flash.answer(g,g.players[id],{id:c.id,choice:3},6002);assert.deepEqual(c.winners.map(w=>w.userId),['b','c','d']);assert.equal(sum(g.players.b),5000);flash.answer(g,g.players.b,{id:c.id,choice:3},999999);assert.equal(sum(g.players.b),5000);assert.throws(()=>flash.answer(g,g.players.e,{id:c.id,choice:3},6003));assert.equal(flash.view(g,'e',false,6004).correct,3);assert.equal(flash.view(g,'a',true,6004).answers.length,4);const c2=flash.start(g,payload,40000);assert.throws(()=>flash.answer(g,g.players.e,{id:c2.id,choice:3},75000));assert.equal(flash.view(g,'e',false,75000).open,false);});
for(const mode of ['cost-markup-v1','supply-demand-v1'])test('prize accounting settles once and survives skipped winner: '+mode,()=>{const g=setup(mode),base=structuredClone(g),c=flash.start(g,payload,1000);flash.answer(g,g.players.a,{id:c.id,choice:3},6000);flash.close(g,c.id,6001);g.players.a.skippedRound=1;base.players.a.skippedRound=1;simulate(g,()=>[]);simulate(base,()=>[]);assert.equal(sum(g.players.a)-sum(base.players.a),5000);assert.equal(g.players.a.reports[0].flashIncome,5000);for(const p of Object.values(g.players)){const r=p.reports[0];assert.equal(r.profit,r.revenue-r.cost-r.fees-r.penalty);}assert.equal(sum(g.players.a),5000);});
test('validation, room membership and pause/phase safeguards',()=>{for(const patch of [{prizes:[-1,0,0]},{prizes:[100001,0,0]},{prizes:[100,200,0]},{correct:4},{seconds:0},{question:''},{options:['x','x','y','z']}])assert.throws(()=>flash.start(setup(),{...payload,...patch}));const g=setup(),c=flash.start(g,payload,1000);assert.throws(()=>flash.answer(g,null,{id:c.id,choice:3},6000));assert.throws(()=>flash.answer(g,g.players.a,{id:'old',choice:3},6000));g.paused=true;assert.throws(()=>flash.answer(g,g.players.a,{id:c.id,choice:3},6000));flash.close(g,c.id,6001);assert.equal(flash.active(c,6002),false);g.phase='results';assert.throws(()=>flash.start(g,payload,7000));});

test('normal restaurant report includes winnings once',()=>{const g=setup(),base=structuredClone(g),c=flash.start(g,payload,1000);flash.answer(g,g.players.a,{id:c.id,choice:3},6000);flash.close(g,c.id,6001);simulate(g,()=>[]);simulate(base,()=>[]);assert.equal(sum(g.players.a)-sum(base.players.a),5000);assert.equal(g.players.a.reports[0].flashIncome,5000);});
