'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true}),base='http://127.0.0.1:3198',suffix=Date.now().toString(36),errors=[];
async function api(c,url,data){const r=await c.request.post(base+'/api'+url,{data});assert.equal(r.status(),200,await r.text());return r.json();}
try{const h=await browser.newContext({viewport:{width:1440,height:1000}}),c=await browser.newContext();await api(h,'/register',{name:'Teacher',username:'host_'+suffix,password:'test-password',teacherLogin:true,teacherKey:'classroom-local'});await api(c,'/register',{name:'Owner',username:'owner_'+suffix,password:'test-password'});
const g=await api(h,'/games',{name:'Teacher controls lab',lessonId:'supply-demand-v1'}),url='/games/'+g.code;await api(c,url+'/join',{restaurant:'Fry Society'});
const t=await h.newPage(),s=await c.newPage(),b=await browser.newPage();for(const p of [t,s,b])p.on('pageerror',e=>errors.push(e.message));await t.goto(base);await t.locator('[data-open]').click();await s.goto(base);await s.locator('[data-open]').click();await b.goto(base+'/?board='+g.code);
await t.locator('[data-control=start]').click();await s.locator('[data-select="1"]').first().click();await s.locator('[name=stock]').fill('20');await s.getByRole('button',{name:'Save price & stock',exact:true}).click();await s.locator('.feedback.success').waitFor();
t.once('dialog',d=>d.dismiss());await t.locator('[data-manage=reset]').click();assert.equal((await h.request.get(base+'/api'+url).then(r=>r.json())).phase,'planning');
t.once('dialog',d=>d.accept('wrong'));await t.locator('[data-manage=delete]').click();await t.getByText('Room code did not match. Nothing changed.',{exact:true}).waitFor();
await t.waitForTimeout(2700);t.once('dialog',d=>d.accept(g.code));await t.locator('[data-manage=reset]').click();await t.locator('[data-control=start]').waitFor();await s.waitForFunction(()=>JSON.parse(render_game_to_text()).game.phase==='lobby');assert.equal((await c.request.get(base+'/api'+url).then(r=>r.json())).player.menu.length,0);
fs.mkdirSync('output/management',{recursive:true});await t.screenshot({path:'output/management/teacher.png',fullPage:true});await t.setViewportSize({width:390,height:844});assert.ok(await t.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await t.screenshot({path:'output/management/mobile.png',fullPage:true});
t.once('dialog',d=>d.accept(g.code));await t.locator('[data-manage=delete]').click();await t.locator('#host-form').waitFor();await s.locator('#join-form').waitFor();await b.getByRole('heading',{name:'Game unavailable'}).waitFor();assert.equal(await t.locator('[data-open]').count(),0);assert.deepEqual(errors,[]);console.log('PASS: cancel, invalid confirmation, reset roster, mobile controls, deletion and student/public updates');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
