const {test}=require('node:test'),assert=require('node:assert/strict');
const {buy,outcomes,price}=require('../lib/mystery-box'),{sum}=require('../lib/achievements'),{newPlayer,simulate}=require('../lib/game'),{initializeLesson}=require('../lib/lessons');
function setup(lesson='cost-markup-v1'){const g=initializeLesson({round:2,phase:'planning',paused:false,penalty:500,players:{}},lesson);for(const id of ['a','b']){const p=newPlayer({id,name:id,badges:[]},id,'🍔','#123456');p.reports=[{round:1,profit:10000,units:1,items:[]}];p.menu=[{id:'1',price:480,markup:100,stock:40,addedRound:1}];g.players[id]=p;}return g;}
test('exactly 30 distinct bounded outcomes with requested distribution',()=>{assert.equal(outcomes.length,30);assert.equal(new Set(outcomes.map(x=>x.title)).size,30);for(const [kind,count] of [['reward',13],['mishap',12],['nothing',5]])assert.equal(outcomes.filter(x=>x.kind===kind).length,count);for(const o of outcomes){assert.ok(o.amount-price>=-1500&&o.amount-price<=1500);if(o.kind==='reward')assert.ok(o.amount-price>0);}});
for(const lesson of ['cost-markup-v1','supply-demand-v1'])test('all outcomes settle exactly once in '+lesson,()=>{for(let i=0;i<30;i++){const g=setup(lesson),base=structuredClone(g),p=g.players.a;const result=buy(g,p,()=>i);assert.equal(sum(p),10000+result.net);assert.throws(()=>buy(g,p,()=>i));for(const x of [g,base]){Object.values(x.players).forEach(p=>p.ready=true);simulate(x,()=>[]);}assert.equal(sum(p),sum(base.players.a)+result.net);assert.equal(p.reports.at(-1).mysteryFees,-result.net);}});
test('eligibility checks and skipped-round settlement',()=>{for(const edit of [g=>g.round=1,g=>g.paused=true,g=>g.phase='results',g=>g.players.a.ready=true,g=>g.players.a.skippedRound=2,g=>g.players.a.reports=[]]){const g=setup();edit(g);assert.throws(()=>buy(g,g.players.a));assert.equal(g.players.a.mysteryBoxes,undefined);}const g=setup(),p=g.players.a;buy(g,p,()=>0);p.skippedRound=2;g.players.b.ready=true;simulate(g,()=>[]);assert.equal(sum(p),11500);});

test('Vinnie unlocks round 4 with exactly tenfold net effects and $300 duds',()=>{const {offer,vinnieOutcomes}=require('../lib/mystery-box');assert.equal(offer(3).price,500);assert.equal(offer(4).price,30000);assert.equal(offer(10).vendor,'Vinnie');assert.equal(vinnieOutcomes.length,30);for(const [kind,n] of [['reward',13],['mishap',12],['nothing',5]])assert.equal(vinnieOutcomes.filter(x=>x.kind===kind).length,n);for(let i=0;i<30;i++){for(const lesson of ['cost-markup-v1','supply-demand-v1']){const g=setup(lesson);g.round=4;g.players.a.reports[0].profit=50000;const baseline=structuredClone(g),p=g.players.a,result=buy(g,p,()=>i);const net=outcomes[i].kind==='nothing'?-30000:(outcomes[i].amount-price)*10;assert.equal(result.price,30000);assert.equal(result.net,net);assert.equal(sum(p),50000+net);assert.notEqual(result.title,outcomes[i].title);for(const x of [g,baseline]){Object.values(x.players).forEach(p=>p.ready=true);simulate(x,()=>[]);}assert.equal(sum(p),sum(baseline.players.a)+net);}}const g=setup();g.round=4;assert.throws(()=>buy(g,g.players.a),/\$300/);assert.equal(g.players.a.mysteryBoxes,undefined);});

test('every tier has bounded outcomes and settles once in both lessons',()=>{const {tiers,offer,describe}=require('../lib/mystery-box');assert.deepEqual(tiers.map(x=>[x.from,x.price]),[[2,500],[4,30000],[6,50000],[8,75000],[10,100000]]);for(const tier of tiers){assert.equal(offer(tier.from).price,tier.price);if(tier.from<10)assert.equal(offer(tier.from+1).price,tier.price);const info=describe(tier.from);assert.ok(info.rewardMax<=75000);assert.ok(info.lossMax<=75000);for(const lesson of ['cost-markup-v1','supply-demand-v1'])for(let i=0;i<30;i++){const g=setup(lesson);g.round=tier.from;g.players.a.reports=[{round:1,profit:200000,units:1,items:[]}];const p=g.players.a,base=structuredClone(g),r=buy(g,p,()=>i);assert.equal(r.net,r.amount-r.price);assert.equal(r.net,r.kind==='nothing'?-tier.price:(outcomes[i].amount-price)*tier.multiplier);assert.equal(sum(p),200000+r.net);for(const x of [g,base]){Object.values(x.players).forEach(p=>p.ready=true);simulate(x,()=>[]);}assert.equal(sum(p),sum(base.players.a)+r.net);}}});
