const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),{createApp}=require('../server');
(async()=>{const app=createApp({dbPath:':memory:',teacherKey:'test-key'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`,browser=await chromium.launch({headless:true});try{
 const h=await browser.newContext(),c=await browser.newContext(),errors=[];
 async function post(ctx,path,data,status=200){const r=await ctx.request.post(base+'/api'+path,{data});assert.equal(r.status(),status,await r.text());return r.json();}async function get(ctx,path){return(await ctx.request.get(base+'/api'+path)).json();}
 await post(h,'/register',{name:'Teacher',username:'pricinghost',password:'test-password',teacherLogin:true,teacherKey:'test-key'});await post(c,'/register',{name:'Owner',username:'pricingowner',password:'test-password'});
 const t=await h.newPage(),s=await c.newPage();[t,s].forEach(p=>p.on('pageerror',e=>errors.push(e.message)));await t.goto(base);await t.locator('#host-form [name=lessonId] option[value="pricing-v1"]').waitFor({state:'attached'});assert.equal(await t.locator('#host-form [name=lessonId] option[value="supply-demand-v1"]').count(),0);
 let g=await post(h,'/games',{name:'Pricing Lab',lessonId:'pricing-v1'}),url='/games/'+g.code;await post(c,url+'/join',{restaurant:'Fry Society'});g=await get(h,url);await post(h,url+'/start',{version:g.version});await s.goto(base);await s.locator(`[data-open="${g.code}"]`).click();await s.locator('#business-plan-form').waitFor();assert.equal(await s.locator('#strategy-form').count(),0);
 await s.locator('#business-plan-form [name=target]').selectOption('teens');await s.locator('#business-plan-form [name=strategy]').selectOption('cost-plus');await s.locator('#business-plan-form button').click();await s.locator('.product[data-select="1"]').click();await s.getByText('Customer fit & free cost-plus calculator',{exact:true}).click();await s.locator('[data-business-calculate]').click();assert.equal(await s.locator('#pricing-form [name=price]').inputValue(),'3.60');await s.locator('#pricing-form [name=stock]').fill('25');assert.equal(await s.locator('#pricing-form [name=amount]').count(),0);await s.locator('#pricing-form button').click();await s.locator('[data-action=ready]:not([disabled])').waitFor();fs.mkdirSync('output/pricing',{recursive:true});await s.locator('.strategy-panel').screenshot({path:'output/pricing/plan.png'});await s.setViewportSize({width:390,height:844});await s.locator('#round-clues').scrollIntoViewIfNeeded();await s.screenshot({path:'output/pricing/mobile.png'});assert.ok(await s.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await s.locator('[data-action=ready]').click();g=await get(h,url);await post(h,url+'/run',{version:g.version});await s.locator('.result-overview').waitFor();await s.locator('details[data-fold$=":results"] > summary').click();await s.getByText('Follow the money',{exact:true}).scrollIntoViewIfNeeded();await s.screenshot({path:'output/pricing/results.png'});
 let state=await get(c,url);assert.ok(state.player.reports[0].business);assert.equal(state.player.mathChecksByRound,undefined);assert.equal(state.business.tracker,undefined);assert.equal(state.player.reports[0].penalty,0);
 // Complete a saved game, including a real bundle and scenario. Check API guards and final report.
 for(let round=2;round<=10;round++){
 g=await get(h,url);await post(h,url+'/next',{version:g.version});state=await get(c,url);const item=state.catalog.find(i=>!state.player.menu.some(x=>x.id===i.id));await post(c,url+'/check',{id:item.id,price:item.expected/100,stock:20});await post(c,url+'/strategy',{target:'families',strategy:round===2?'bundle':'competitive',focus:'1',companion:item.id,discount:15,position:'match',scenario:round===3?'penetration':undefined});await post(c,url+'/ready',{});await post(c,url+'/strategy',{target:'teens',strategy:'premium'},400);g=await get(h,url);await post(h,url+'/run',{version:g.version});}
 await s.reload();await s.locator(`[data-open="${g.code}"]`).click();await s.locator('details[data-fold$=":results"] > summary').click();await s.locator('.business-season').waitFor();await s.locator('.business-season').screenshot({path:'output/pricing/season.png'});state=await get(c,url);assert.equal(state.phase,'complete');assert.equal(state.player.reports.length,10);assert.ok(state.player.reports[1].items.some(i=>i.discount>0));assert.equal(state.player.reports[2].business.scenario.correct,true);assert.ok((await get(c,'/leaderboard?lessonId=pricing-v1')).board.length===1);assert.equal((await get(c,'/leaderboard?lessonId=cost-markup-v1')).board.length,0);
 await t.reload();await t.locator(`[data-open="${g.code}"]`).click();await t.getByText('Business decisions · teacher view',{exact:true}).waitFor();await t.screenshot({path:'output/pricing/teacher.png'});assert.deepEqual(errors,[]);console.log('PASS new lesson selector, research/plan/calculator, no markup grading, ten rounds, bundle, delayed scenario, final report, separate boards, teacher and mobile');
 }finally{await browser.close();await new Promise(r=>app.server.close(r));app.db.close();}})().catch(e=>{console.error(e);process.exitCode=1});
