const {test}=require('node:test'),assert=require('node:assert/strict');
const lesson=require('../lib/lessons/pricing-v1'),{initializeLesson}=require('../lib/lessons'),{newPlayer,simulate,pricing}=require('../lib/game'),{sum}=require('../lib/achievements');
function setup(strategy='cost-plus',target='teens',multiplier=1){const g=initializeLesson({round:3,phase:'planning',players:{},penalty:500},'pricing-v1');g.rules.events=g.rules.events.map(()=>g.rules.pricing.events[0]);const p=g.players.a=newPlayer({id:'a',name:'Owner',badges:[]},'A','🍔','#123456');p.menu=[{id:'1',price:Math.round(450*multiplier),stock:80,markup:0,addedRound:1},{id:'40',price:Math.round(570*multiplier),stock:80,markup:0,addedRound:3}];if(strategy==='loss-leader')p.menu[1].price=250;if(strategy==='psychological')p.menu.forEach(x=>x.price=Math.floor(x.price/100)*100+99);lesson.choose(g,p,{target,strategy,focus:'40',companion:'1',discount:15,position:'match'});p.ready=true;return {g,p};}
test('all eight strategies and six targets produce finite reconciled results with bounded stock',()=>{for(const s of lesson.rules.pricing.strategies)for(const m of lesson.rules.pricing.markets){const {g,p}=setup(s.id,m.id);simulate(g,()=>[]);const r=p.reports[0],b=r.business;assert.equal(r.profit,r.revenue-r.cost-r.fees-r.penalty);assert.equal(b.cogs+b.waste,r.cost);assert.equal(b.grossProfit-b.operatingExpenses,r.profit);assert.ok(Number.isFinite(sum(p)));assert.ok(b.transactions<=108);assert.ok(b.satisfaction===null||(b.satisfaction>=0&&b.satisfaction<=100));for(const x of r.items){assert.ok(x.units<=x.prepared&&x.units>=0);assert.ok(Number.isInteger(x.revenue)&&Number.isInteger(x.cost));assert.equal(x.leftover+x.units,x.prepared);}assert.equal(r.penalty,0);}});
test('bundle conserves stock, discount cents, and revenue for both items',()=>{const {g,p}=setup('bundle');simulate(g,()=>[]);const r=p.reports[0];assert.equal(r.items[0].units,r.items[1].units);const units=r.items[0].units;assert.equal(r.revenue,units*Math.round((450+570)*.85));assert.equal(r.items.reduce((n,i)=>n+i.discount,0),units*1020-r.revenue);assert.equal(r.business.transactions,units);});
test('high prices cannot generate infinite revenue; stock waste remains a loss',()=>{const {g,p}=setup('premium','budget',10);p.menu.forEach(x=>x.price=5000);simulate(g,()=>[]);assert.ok(p.reports[0].profit<0);assert.ok(p.reports[0].units<5);});
test('customers and actual competitor offers change purchase outcomes',()=>{const a=setup('premium','luxury',1.3),b=setup('premium','budget',1.3);simulate(a.g,()=>[]);simulate(b.g,()=>[]);assert.notEqual(a.p.reports[0].revenue,b.p.reports[0].revenue);const solo=setup(),rival=setup();const q=structuredClone(rival.p);q.userId='b';q.owner='Rival';q.menu.forEach(x=>x.price=250);rival.g.players.b=q;const before=lesson.simulateRound(solo.g,[solo.p]).a.transactions,after=lesson.simulateRound(rival.g,Object.values(rival.g.players)).a.transactions;assert.notEqual(before,after);});
test('loss-leader cross-sales consume remaining stock and cannot exceed 25 percent of lead purchases',()=>{const {g,p}=setup('loss-leader');const x=lesson.simulateRound(g,[p]).a;assert.ok((x.crossSales||0)<=Math.floor(x.items['40'].units*.25));assert.ok(x.items['1'].units<=80);});
test('strategy gates, snapshot stability, scenario privacy and no math grading',()=>{const {g,p}=setup();p.ready=false;lesson.choose(g,p,{target:'budget',strategy:'bundle',focus:'1',companion:'1'});assert.match(lesson.readyError(g,p),/different/);lesson.choose(g,p,{target:'teens',strategy:'loss-leader',focus:'40'});assert.match(lesson.readyError(g,p),/below/);lesson.choose(g,p,{target:'teens',strategy:'skimming',focus:'1'});assert.match(lesson.readyError(g,p),/wild/);assert.throws(()=>lesson.choose(g,p,{target:'invalid',strategy:'premium'}));assert.equal(lesson.publicResearch(g,p,false).scenario.answer,undefined);assert.equal(lesson.publicResearch(g,p,false).tracker,undefined);const saved=JSON.stringify(g.rules.events);lesson.market(g);assert.equal(JSON.stringify(g.rules.events),saved);pricing(g,p,{id:'40',price:4.99,stock:30});assert.equal(p.mathChecksByRound,undefined);assert.equal(p.wrongRounds.length,0);});
test('ten rounds preserve business reports, flash rewards and bonus accounting',()=>{const g=initializeLesson({round:1,phase:'planning',players:{},penalty:500},'pricing-v1'),p=g.players.a=newPlayer({id:'a',name:'A',badges:[]},'A','🍔','#123456');for(let round=1;round<=10;round++){g.round=round;g.phase='planning';p.ready=false;const item=g.rules.catalog.find(i=>i.round<=round&&!p.menu.some(x=>x.id===i.id));pricing(g,p,{id:item.id,price:item.expected/100,stock:15});lesson.choose(g,p,{strategy:round%2?'cost-plus':'competitive',target:'families'});p.flashRewards??=[];p.flashRewards.push({id:'flash'+round,round,amount:1000});p.ready=true;simulate(g,()=>[]);assert.equal(p.reports.at(-1).flashIncome,1000);assert.ok(p.reports.at(-1).business);assert.equal(p.reports.at(-1).profit,p.reports.at(-1).revenue-p.reports.at(-1).cost-p.reports.at(-1).fees);}assert.equal(g.phase,'complete');assert.equal(p.reports.length,10);assert.equal(sum(p),p.reports.reduce((n,r)=>n+r.profit,0));});
test('balance sample has multiple winning strategies across customer and stock conditions',()=>{const winners=new Set();for(const target of lesson.rules.pricing.markets)for(const stock of [15,35,80]){let best=-Infinity,winner;for(const s of lesson.rules.pricing.strategies)for(const multiplier of [.55,.7,.85,1,1.15,1.3,1.5,1.8]){const {g,p}=setup(s.id,target.id,multiplier);p.menu.forEach(i=>i.stock=stock);simulate(g,()=>[]);if(p.reports[0].profit>best){best=p.reports[0].profit;winner=s.id;}}winners.add(winner);}assert.ok(winners.size>=3,`Winners in tested conditions: ${[...winners]}`);console.log('Balance sample winners:',[...winners].join(', '));});
test('market events and temporary switching consequences apply through customer behavior',()=>{const {g,p}=setup('cost-plus','teens'),normal=lesson.simulateRound(g,[p]).a;g.rules.events[2]=g.rules.pricing.events.find(e=>e.id==='supplier');const expensive=lesson.simulateRound(g,[p]).a;assert.ok(expensive.items['1'].cost>normal.items['1'].cost);g.rules.events[2]=g.rules.pricing.events.find(e=>e.id==='price-war');assert.ok(lesson.simulateRound(g,[p]).a.transactions<=normal.transactions);p.reports.push({round:2,business:{strategy:'premium',target:'luxury',loyalty:.1}});assert.equal(lesson.simulateRound(g,[p]).a.switched,true);p.reports[0].business.strategy='cost-plus';p.reports[0].business.target='teens';assert.equal(lesson.simulateRound(g,[p]).a.switched,false);});
test('alliances, boxes, flash prizes and next-round backstab transfers coexist without double accounting',()=>{
 const {g,p}=setup(),q=structuredClone(p);q.userId='b';q.owner='B';g.players.b=q;g.sabotageMode='sales';
 for(const player of [p,q]){player.ready=false;player.reports=[{round:2,profit:50000,revenue:60000,items:[],units:0}];}
 const alliances=require('../lib/alliances'),sabotage=require('../lib/sabotage');alliances.act(g,p,'allianceInvite',{target:'b'});alliances.act(g,q,'allianceAccept',{id:g.allianceInvites[0].id});
 require('../lib/mystery-box').buy(g,p,()=>0);p.flashRewards=[{id:'f',round:3,amount:1000}];sabotage.spin(g,p,{target:'b',cost:1000},()=>0);p.ready=q.ready=true;simulate(g,()=>[]);assert.ok(p.reports.at(-1).allianceSavings>0);assert.equal(p.reports.at(-1).flashIncome,1000);
 g.round=4;g.phase='planning';for(const player of [p,q]){player.ready=false;pricing(g,player,{id:'2',price:4.9,stock:20});lesson.choose(g,player,{strategy:'cost-plus',target:'teens'});player.ready=true;}
 simulate(g,()=>[]);assert.equal(g.sabotageClaims[0].settled,true);const amount=Math.round(q.reports.at(-1).revenue*.15);assert.equal(p.reports.at(-1).sabotageIncome,amount);assert.equal(q.reports.at(-1).sabotageStolen,amount);for(const player of [p,q]){const r=player.reports.at(-1);assert.equal(r.profit,r.revenue-r.cost-r.fees);assert.equal(r.business.grossProfit-r.business.operatingExpenses,r.profit);}const total=sum(p)+sum(q);sabotage.settle(g);assert.equal(sum(p)+sum(q),total);
});
test('skipped business retains a zero-share report with final financial reconciliation',()=>{const {g,p}=setup(),q=structuredClone(p);q.userId='b';g.players.b=q;p.skippedRound=g.round;p.flashRewards=[{round:g.round,amount:1000}];simulate(g,()=>[]);const r=p.reports[0];assert.equal(r.business.marketShare,0);assert.ok(r.business.marketTransactions>0);assert.equal(r.business.grossProfit-r.business.operatingExpenses,r.profit);assert.equal(r.profit,1000);});
