'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true}),base=process.env.TEST_URL||'http://127.0.0.1:3198',suffix=Date.now().toString(36),errors=[];
 const teacher=await browser.newContext({viewport:{width:1440,height:1050}}),student=await browser.newContext({viewport:{width:1440,height:1050}}),t=await teacher.newPage(),s=await student.newPage();fs.mkdirSync('output/business-math-setup',{recursive:true});
 for(const p of [t,s]){p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())})}
 try{
  await t.goto(base);await t.locator('[data-action=teacher-entry]').click();await t.getByRole('heading',{name:'Welcome back, teacher.'}).waitFor();await t.screenshot({path:'output/business-math-setup/teacher-login.png',fullPage:true});
  await t.setViewportSize({width:390,height:844});await t.screenshot({path:'output/business-math-setup/teacher-mobile.png',fullPage:true});assert.ok(await t.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await t.setViewportSize({width:1440,height:1050});
  await t.locator('[data-action=register-tab]').click();await t.locator('[name=name]').fill('Ms. Rivera');await t.locator('[name=username]').fill('teacher_'+suffix);await t.locator('[name=password]').fill('school-test-password');await t.locator('[name=teacherKey]').fill('classroom-local');await t.locator('#auth-form >button').click();await t.locator('#host-form').waitFor();assert.equal(await t.locator('#host-form [name=teacherKey]').count(),0);
  await t.locator('#host-form [name=name]').fill('Week 1 · Cost & Markup');await t.locator('#host-form >button').click();await t.waitForFunction(()=>JSON.parse(window.render_game_to_text()).game?.code);const code=await t.evaluate(()=>JSON.parse(window.render_game_to_text()).game.code);
  await s.goto(base);await s.locator('[name=name]').fill('Avery');await s.locator('[name=username]').fill('student_'+suffix);await s.locator('[name=password]').fill('school-test-password');await s.locator('#auth-form >button').click();await s.locator('#join-form').waitFor();assert.equal(await s.locator('select[name=restaurant] option').count(),51);assert.equal(await s.locator('[name=icon] option').count(),32);assert.equal(await s.locator('[name=color] option').count(),16);assert.equal(await s.locator('input[name=restaurant]').count(),0);
  await s.locator('[name=code]').fill(code);await s.locator('[name=restaurant]').selectOption('The Last Fry');await s.locator('[name=icon]').selectOption('🍦');await s.locator('[name=color]').selectOption('#373f51');assert.equal(await s.locator('#restaurant-preview strong').innerText(),'The Last Fry');await s.screenshot({path:'output/business-math-setup/restaurant-choices.png',fullPage:true});await s.setViewportSize({width:390,height:844});await s.screenshot({path:'output/business-math-setup/choices-mobile.png',fullPage:true});assert.ok(await s.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await s.setViewportSize({width:1440,height:1050});
  await s.locator('#join-form >button').click();await s.waitForFunction(()=>JSON.parse(window.render_game_to_text()).game?.player?.restaurant==='The Last Fry');await s.reload();await s.locator('[data-open]').click();await s.waitForFunction(()=>JSON.parse(window.render_game_to_text()).game?.player);const g=await s.evaluate(()=>JSON.parse(window.render_game_to_text()).game);assert.equal(g.player.icon,'🍦');assert.equal(g.player.color,'#373f51');
  await t.locator('[data-action=logout]').click();await t.locator('[data-action=login-tab]').click();await t.locator('[name=username]').fill('teacher_'+suffix);await t.locator('[name=password]').fill('school-test-password');await t.locator('[name=teacherKey]').fill('classroom-local');await t.locator('#auth-form >button').click();await t.locator('#host-form').waitFor();assert.equal(await t.locator('#host-form [name=teacherKey]').count(),0);await t.locator('[data-open]').click();await t.locator('[data-control=start]').click();await s.waitForFunction(()=>JSON.parse(window.render_game_to_text()).game?.phase==='planning');await s.screenshot({path:'output/business-math-setup/chosen-restaurant.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: first-page teacher registration/login, verified hosting session, 50 enforced name choices, 32 signs, 16 colors, live preview, reload persistence, mobile layout and teacher resume.');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
