const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const themes=require('../public/themes'),{createApp}=require('../server');
(async()=>{const app=createApp({dbPath:':memory:',teacherKey:'test-key'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`,browser=await chromium.launch({headless:true});try{
 const h=await browser.newContext(),c=await browser.newContext(),errors=[];
 async function post(ctx,path,data,status=200){const r=await ctx.request.post(base+'/api'+path,{data});assert.equal(r.status(),status,await r.text());return r.json();}
 await post(h,'/register',{name:'Teacher',username:'themehost',password:'test-password',teacherLogin:true,teacherKey:'test-key'});await post(c,'/register',{name:'Owner',username:'themeowner',password:'test-password'});
 await post(c,'/profile',{palette:'invalid'},400);await post(c,'/profile',{colorMode:'invalid'},400);
 let g=await post(h,'/games',{name:'Theme Kitchen'}),url='/games/'+g.code;await post(c,url+'/join',{restaurant:'Fry Society'});g=await(await h.request.get(base+'/api'+url)).json();await post(h,url+'/start',{version:g.version});
 const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.locator(`[data-open="${g.code}"]`).click();await p.locator('.product[data-select="35"]').click();await p.locator('#pricing-form [name=markup]').fill('123');await p.locator('[data-action=appearance]').click();assert.equal(await p.locator('.theme-choice').count(),10);fs.mkdirSync('output/themes',{recursive:true});
 for(const t of themes){await p.locator(`[data-palette="${t.id}"].theme-choice`).click();await p.waitForFunction(id=>document.documentElement.dataset.palette===id,t.id);for(const mode of ['light','dark']){await p.locator(`[data-mode="${mode}"]`).click();await p.waitForFunction(m=>document.documentElement.dataset.theme===m,mode);await p.screenshot({path:`output/themes/${t.id}-${mode}.png`});}}
 await p.locator('[data-close-appearance]').click();assert.equal(await p.locator('#pricing-form [name=markup]').inputValue(),'123');await p.screenshot({path:'output/themes/game-dark.png'});
 const me=await(await c.request.get(base+'/api/me')).json();assert.equal(me.user.palette,'cherry');assert.equal(me.user.colorMode,'dark');const teacher=await(await h.request.get(base+'/api/me')).json();assert.equal(teacher.user.palette,'classic');
 await p.reload();assert.equal(await p.locator('html').getAttribute('data-palette'),'cherry');const other=await browser.newContext();await post(other,'/login',{username:'themeowner',password:'test-password'});const q=await other.newPage();await q.goto(base);await q.locator('[data-action=appearance]').waitFor();assert.equal(await q.locator('html').getAttribute('data-palette'),'cherry');assert.equal(await q.locator('html').getAttribute('data-theme'),'dark');
 await q.setViewportSize({width:390,height:844});await q.locator('[data-action=appearance]').click();await q.screenshot({path:'output/themes/mobile.png'});assert.ok(await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await q.keyboard.press('Escape');assert.equal(await q.locator('#appearance-dialog').count(),0);
 const hp=await h.newPage();await hp.goto(base);await hp.locator(`[data-open="${g.code}"]`).click();await hp.locator('[data-action=appearance]').click();await hp.locator('[data-palette=arcade].theme-choice').click();await hp.locator('[data-close-appearance]').click();await hp.screenshot({path:'output/themes/teacher.png'});
 assert.deepEqual(errors,[]);console.log('PASS all ten themes in both modes, account isolation, validation, new-device persistence, unsaved input preservation, mobile dialog and teacher dashboard');
 }finally{await browser.close();await new Promise(r=>app.server.close(r));app.db.close();}})().catch(e=>{console.error(e);process.exitCode=1});
