'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true}),base='http://127.0.0.1:3198',suffix=Date.now().toString(36);async function api(c,url,data){const r=await c.request.post(base+'/api'+url,{data});assert.equal(r.status(),200,await r.text());return r.json();}
try{fs.mkdirSync('output/tutorial',{recursive:true});for(const [index,lessonId] of ['cost-markup-v1','supply-demand-v1'].entries()){
const h=await browser.newContext(),c=await browser.newContext({viewport:{width:390,height:844}}),errors=[];
await api(h,'/register',{name:'Teacher',username:'th'+index+suffix,password:'test-password',teacherLogin:true,teacherKey:'classroom-local'});await api(c,'/register',{name:'Owner',username:'ts'+index+suffix,password:'test-password'});
let g=await api(h,'/games',{name:'Tutorial class',lessonId}),url='/games/'+g.code;g=await api(c,url+'/join',{restaurant:'Fry Society'});const s=await c.newPage();s.on('pageerror',e=>errors.push(e.message));await s.goto(base);await s.locator('[data-open]').click();assert.equal(await s.locator('.tutorial-card').count(),0);
g=await api(h,url+'/start',{version:g.version});await s.locator('.tutorial-card').waitFor();await s.screenshot({path:`output/tutorial/${lessonId}.png`,fullPage:true});assert.ok(await s.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await s.locator('[data-tutorial=next]').click();await s.locator('[data-tutorial=back]').click();await s.locator('[data-tutorial=next]').click();await s.locator('[data-tutorial=next]').click();assert.match(await s.locator('.tutorial-card').innerText(),index?/Save price & stock/:/Check math & save price/);await s.locator('[data-tutorial=next]').click();await s.locator('[data-tutorial=done]').click();await s.locator('[data-tutorial=replay]').waitFor();
await s.reload();await s.locator('[data-open]').click();assert.equal(await s.locator('.tutorial-card').count(),0);await s.locator('[data-tutorial=replay]').click();await s.locator('[data-tutorial=skip]').click();await s.locator('[data-select="1"]').first().click();if(index){await s.locator('[name=stock]').fill('30');}else{await s.locator('[name=markup]').fill('100');await s.locator('[name=amount]').fill('2.40');await s.locator('[name=price]').fill('4.80');}await s.locator('#pricing-form button').click();await s.locator('.feedback.success').waitFor();if(index){await api(c,url+'/strategy',{clue:'demand',demand:'hold',price:'hold',stock:'hold'});await s.waitForTimeout(2800);}await s.locator('[data-action=ready]').click();
g=await h.request.get(base+'/api'+url).then(r=>r.json());g=await api(h,url+'/reset',{version:g.version,confirmCode:g.code});await s.waitForFunction(()=>JSON.parse(render_game_to_text()).game.phase==='lobby');await api(h,url+'/start',{version:g.version});await s.locator('.tutorial-card').waitFor();assert.deepEqual(errors,[]);await h.close();await c.close();}
console.log('PASS: both tutorials, round-one trigger, back/next/skip/replay, persistence, reset, mobile and real price submission');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
