'use strict';
// Versioned classroom scenarios: classification depends on the stated customer
// need and offer, rather than a permanent label attached to a business category.
const scenarios=[
 {title:'The lunchtime burger battle',context:'Your restaurant sells fast, ready-to-eat burger lunches to office workers.',cases:[['burger','Burger Express','Another counter offers similar burger lunches to the same office workers.','direct','Both restaurants offer similar fast lunches to the same customers.']],pressure:1,boosts:[1,1,1]},
 {title:'Lunch can come from somewhere else',context:'Your restaurant serves hot, made-to-order lunches to office workers.',cases:[['grocery','Market Street Grocer','The grocery store promotes ingredients for packed lunches made at home. Workers could bring those lunches instead of visiting you.','indirect','Packed lunches meet the same need to eat lunch through a different product and preparation method.']],pressure:1,boosts:[1,1,1]},
 {title:'A rival advertises bargain lunches',context:'You and another fast-food counter serve workers looking for a quick lunch. Customers are comparing prices.',cases:[['bargain','Budget Burger','A nearby fast-food counter advertises similar lunch meals at low prices to your customers.','direct','The rival offers similar fast-food meals to the same lunch customers.']],pressure:.90,boosts:[1.12,1.05,1.07]},
 {title:'Dinner without a restaurant visit',context:'Your restaurant sells ready-to-eat family dinners. Some families have time to cook, while others want food immediately.',cases:[['kits','Dinner Kit Club','A meal-kit service delivers ingredients and recipes for families to cook dinner at home.','indirect','Meal kits solve the dinner need through home preparation instead of a ready-to-eat restaurant meal.']],pressure:.92,boosts:[1.05,1.07,1.12]},
 {title:'Another quick-service counter arrives',context:'Festival visitors are choosing between fast-food lunch counters. Some want variety, while others want familiar value.',cases:[['wrap','Wrap Rocket','A new quick-service restaurant offers ready-to-eat lunch combos to the same festival visitors.','direct','Different menu items can still be direct competition when they offer a similar quick-service meal to the same customers.']],pressure:.88,boosts:[1.06,1.13,1.08]},
 {title:'Two ways to win dinner customers',context:'Your restaurant competes for families deciding what to eat tonight. Some want takeaway; others are willing to cook.',cases:[['pizza','Pizza Dash','A takeaway restaurant offers ready-to-eat family meals for collection tonight.','direct','Both restaurants sell ready-to-eat takeaway dinners to the same families.'],['groceries','Cook-at-Home Market','A supermarket promotes a basket of ingredients and a recipe for a family dinner.','indirect','The ingredients meet the same dinner need through home cooking, a different offering.']],pressure:.86,boosts:[1.10,1.07,1.12]},
 {title:'Look at the offer, not just the sign',context:'Your counter sells ready-to-eat hot lunch boxes to office workers. Customers are watching their budgets.',cases:[['deli','The Grocery Deli Counter','Inside a grocery store, this counter sells similar ready-to-eat hot lunch boxes to the same office workers.','direct','In this situation the deli offers the same kind of ready-to-eat lunch to the same customers; being inside a grocery store does not make it indirect.'],['packed','Home Lunch Bundle','Another grocery offer bundles raw ingredients for workers to prepare packed lunches at home.','indirect','This alternative meets the lunch need through home preparation, unlike the ready-to-eat counters.']],pressure:.85,boosts:[1.14,1.04,1.06]},
 {title:'The weekend picnic decision',context:'Your restaurant serves fast meals to park visitors who want to eat during an afternoon out.',cases:[['kiosk','Parkside Grill','A walk-up grill sells similar ready-to-eat fast meals to those park visitors.','direct','Both businesses offer ready-to-eat fast meals for the same visit.'],['picnic','Picnic Pantry','A shop sells picnic ingredients and reusable lunch supplies for visitors to assemble their own meal.','indirect','A self-assembled picnic meets the same eating need in a different way.']],pressure:.89,boosts:[1.06,1.12,1.09]},
 {title:'A quiet day, several alternatives',context:'Your restaurant sells quick lunches to workers with limited time and money.',cases:[['quick','Quick Bite Counter','A competing fast-food counter sells similar lunch meals to those workers.','direct','The offer and intended lunch customers closely match yours.'],['vending','Office Snack Station','An office vending service offers packaged snacks; some workers use these instead of buying a restaurant lunch.','indirect','Packaged snacks can substitute for the eating need without offering the same restaurant meal service.']],pressure:.90,boosts:[1.09,1.05,1.10]},
 {title:'The final celebration',context:'Your restaurant serves quick, ready-to-eat meals to families attending a neighborhood celebration.',cases:[['festival','Festival Meal Counter','Another quick-service counter sells similar ready-to-eat meals to the same families.','direct','Both counters provide similar meals for the same occasion and customers.'],['cookout','Backyard Cookout Packs','A retailer sells ingredients and grill supplies for families to hold their own celebration meal at home.','indirect','A home cookout meets the celebration-meal need through a different product and activity.']],pressure:.86,boosts:[1.08,1.12,1.10]},
];
const reasons=[{id:'similar',label:'A similar meal or service for the same customers and occasion.'},{id:'alternative',label:'A different offering that satisfies the same customer need.'},{id:'nearby',label:'It is nearby, so it must be the same type of competitor.'}];
const strategies=[
 {id:'value',label:'Advertise value',description:'Run a value-focused campaign. Costs $8 this round and can attract more customers; your actual menu prices stay under your control.',reason:'budget',fee:800,costFactor:1},
 {id:'differentiate',label:'Make the offer distinctive',description:'Use distinctive ingredients and presentation. Ingredient costs rise 4%; the campaign can attract customers looking for variety.',reason:'distinct',fee:0,costFactor:1.04},
 {id:'convenience',label:'Make pickup easier',description:'Add a pickup helper for $10 this round. Easier pickup can attract customers who value convenience.',reason:'speed',fee:1000,costFactor:1},
 {id:'hold',label:'Keep the current approach',description:'Avoid extra campaign costs. Competitors may still take some demand; you can adjust actual prices and stock yourself.',reason:'cost',fee:0,costFactor:1},
];
const strategyReasons=[{id:'budget',label:'Highlighting value may attract price-conscious customers, but the campaign costs money.'},{id:'distinct',label:'A distinctive offer may attract customers seeking variety, but ingredients cost more.'},{id:'speed',label:'Easier pickup may attract customers who value convenience, but extra help costs money.'},{id:'cost',label:'Keeping the current approach avoids extra costs, but does not counter the loss of demand.'},{id:'guarantee',label:'This strategy guarantees the highest profit regardless of price, stock, or customers.'}];
const enabled=g=>g.lessonId==='supply-demand-v1'&&g.competitionEnabled===true;
const record=(p,round)=>(p.competitionResponses||[]).find(x=>x.round===round);
function briefing(g){if(!enabled(g))return null;const s=scenarios[g.round-1];return {title:s.title,context:s.context,cases:s.cases.map(([id,name,text])=>({id,name,text})),reasons,strategies:g.round>=3?strategies.map(({id,label,description})=>({id,label,description})):[],strategyReasons:g.round>=3?strategyReasons:[]};}
function choose(g,p,b){const check=(ok,msg)=>{if(!ok)throw Object.assign(new Error(msg),{status:400});};check(enabled(g),'Competition challenges are not enabled for this lesson.');check(g.phase==='planning'&&!g.paused&&!p.ready&&p.skippedRound!==g.round,'Complete the challenge during open planning before submitting.');check(!record(p,g.round),'Your answer is already saved. Review the feedback and use it in your business decisions.');const s=scenarios[g.round-1];check(Array.isArray(b.answers)&&b.answers.length===s.cases.length,'Answer each competitor question.');
 const answers=s.cases.map(([id,name,text,type,explanation])=>{const a=b.answers.find(x=>x&&x.id===id);check(a&&['direct','indirect'].includes(a.type)&&reasons.some(r=>r.id===a.reason),'Choose a classification and reason for each competitor.');return {id,name,type:a.type,reason:a.reason,reasonLabel:reasons.find(x=>x.id===a.reason).label,classificationCorrect:a.type===type,reasonCorrect:a.reason===(type==='direct'?'similar':'alternative'),correctType:type,explanation};});
 let strategy=null;if(g.round>=3){strategy=strategies.find(x=>x.id===b.strategy);check(strategy&&strategyReasons.some(x=>x.id===b.strategyReason),'Choose a business response and its reasoning.');}
 const response={round:g.round,title:s.title,context:s.context,answers,strategy:strategy?.id||null,strategyLabel:strategy?.label||null,strategyReasonLabel:strategy?strategyReasons.find(x=>x.id===b.strategyReason).label:null,strategyReason:strategy?b.strategyReason:null,strategyReasonCorrect:strategy?b.strategyReason===strategy.reason:null,strategyExplanation:strategy?strategyReasons.find(x=>x.id===strategy.reason).label:null};
 (p.competitionResponses??=[]).push(response);return response;
}
function readyError(g,p){return enabled(g)&&!record(p,g.round)?'Complete this round’s Competition Challenge before submitting. Incorrect answers do not block you.':null;}
function effects(g,p){if(!enabled(g)||g.round<3||!record(p,g.round))return {demand:1,cost:1,fee:0};const s=scenarios[g.round-1],r=record(p,g.round),strategy=strategies.find(x=>x.id===r.strategy),index=strategies.indexOf(strategy);return {demand:s.pressure*(index<3?s.boosts[index]:1),cost:strategy.costFactor,fee:strategy.fee};}
function report(g,p){if(!enabled(g)||!record(p,g.round))return null;const r=structuredClone(record(p,g.round)),s=scenarios[g.round-1],strategy=strategies.find(x=>x.id===r.strategy);return {...r,effects:effects(g,p),strategyLabel:strategy?.label||null,feedback:g.round<3?'This introductory challenge does not change sales or costs. Use the explanation to distinguish similar offers from different ways to meet the same need.':`Competitors reduced potential demand. ${strategy.id==='hold'?'You avoided extra campaign costs and accepted that pressure.':strategy.id==='value'?'Your $8 value campaign attracted some potential customers. Your actual prices still influence whether they buy.':strategy.id==='differentiate'?'Your distinctive offer attracted some potential customers, while ingredient costs rose 4%.':'Your $10 pickup helper attracted some potential customers seeking convenience.'} Prices, prepared stock, and market conditions still determine sales and profit. This is a simulated effect, not a guarantee that this strategy is always best.`,strategyExplanation:strategy?strategyReasons.find(x=>x.id===strategy.reason).label:null};}
function summary(p,round){const list=p.competitionResponses||[];const count=rows=>({classificationRight:rows.reduce((n,r)=>n+r.answers.filter(a=>a.classificationCorrect).length,0),classificationTotal:rows.reduce((n,r)=>n+r.answers.length,0),reasonRight:rows.reduce((n,r)=>n+r.answers.filter(a=>a.reasonCorrect).length,0),reasonTotal:rows.reduce((n,r)=>n+r.answers.length,0),strategyReasonRight:rows.filter(r=>r.strategyReasonCorrect===true).length,strategyReasonTotal:rows.filter(r=>r.strategy!==null).length});return {round:count(list.filter(r=>r.round===round)),total:count(list),current:record(p,round)||null,history:list};}
module.exports={enabled,briefing,choose,record,readyError,effects,report,summary,scenarios,strategies};
