"use strict";
// Costs and prices use integer cents throughout the simulation.
const rows = [
  ["Classic Burger", "🍔", 240, "Burgers", 450, 1],
  ["Crispy Chicken", "🥪", 260, "Chicken", 490, 1],
  ["Street Tacos", "🌮", 190, "Tacos", 380, 1],
  ["Personal Pizza", "🍕", 280, "Pizza", 520, 1],
  ["Loaded Fries", "🍟", 160, "Sides", 340, 1],
  ["Lemonade", "🍋", 60, "Drinks", 190, 2],
  ["Chocolate Shake", "🥤", 120, "Drinks", 320, 2],
  ["Churro Bites", "🥨", 90, "Desserts", 260, 2],
  ["Onion Rings", "🧅", 110, "Sides", 280, 2],
  ["Veggie Wrap", "🥬", 200, "Wraps", 420, 2],
  ["BBQ Sliders", "🍔", 290, "Burgers", 560, 3],
  ["Hot Honey Chicken", "🍗", 310, "Chicken", 590, 3],
  ["Cookie Sundae", "🍨", 150, "Desserts", 370, 3],
  ["Fish Tacos", "🌮", 280, "Tacos", 530, 4],
  ["Mac & Cheese", "🧀", 170, "Sides", 370, 4],
  ["Berry Fizz", "🫐", 100, "Drinks", 280, 4],
  ["Waffle Burger", "🧇", 340, "Burgers", 650, 5],
  ["Pizza Cone", "🍕", 270, "Pizza", 560, 5],
  ["Donut Ice Cream", "🍩", 210, "Desserts", 470, 5],
  ["Truffle Sliders", "🍔", 480, "Burgers", 850, 6],
  ["Mega Sundae", "🍧", 390, "Desserts", 720, 6],
  ["Dragonfruit Cooler", "🐉", 190, "Drinks", 440, 6],
  ["Pickle Shake", "🥒", 180, "Drinks", 420, 7],
  ["Rainbow Tacos", "🌈", 320, "Tacos", 650, 7],
  ["Sushi Burrito", "🍣", 460, "Wraps", 820, 7],
  ["Gold-Dust Fries", "✨", 520, "Sides", 950, 8],
  ["Monster Burger", "👹", 620, "Burgers", 1100, 8],
  ["Lava Cake Shake", "🌋", 420, "Drinks", 790, 8],
  ["Cotton Candy Burrito", "🍭", 350, "Desserts", 710, 9],
  ["Volcano Bowl", "🔥", 510, "Bowls", 960, 9],
  ["Meteor Meatballs", "☄️", 440, "Sides", 840, 9],
  ["UFO Burger", "🛸", 590, "Burgers", 1150, 10],
  ["Galaxy Shake", "🌌", 460, "Drinks", 890, 10],
  ["Unicorn Nachos", "🦄", 410, "Sides", 820, 10],
];
const catalog = rows.map((r, i) => ({
  id: String(i + 1),
  name: r[0],
  icon: r[1],
  cost: r[2],
  category: r[3],
  expected: r[4],
  round: r[5],
  wild: i >= 21,
  highCost: r[2] >= 400,
  popularity: 52 + (i % 5) * 5,
  sensitivity: i >= 21 ? 1.5 : 2.3,
}));
const promotions = [
  {
    id: "none",
    name: "No promotion",
    description: "Regular prices. No extra fee.",
    factor: 1,
  },
  {
    id: "bogo",
    name: "Buy one, get one free",
    description: "Two units served for one selling price. Demand +45%.",
    factor: 1.45,
  },
  {
    id: "half",
    name: "Second item half off",
    description: "Two units served for 1.5× the selling price. Demand +30%.",
    factor: 1.3,
  },
  {
    id: "ten",
    name: "10% off",
    description: "Selected item 10% off. Demand +12%.",
    factor: 1.12,
  },
  {
    id: "twenty",
    name: "20% off",
    description: "Selected item 20% off. Demand +22%.",
    factor: 1.22,
  },
  {
    id: "dollar",
    name: "$1 off",
    description: "Selected item $1 off. Demand +18%.",
    factor: 1.18,
  },
  {
    id: "bundle",
    name: "Meal deal",
    description:
      "Selected item + a side or drink, 15% off their combined price. Demand +20%.",
    factor: 1.2,
    companion: true,
  },
  {
    id: "freeSide",
    name: "Free side",
    description: "Selected item includes a free side. Demand +28%.",
    factor: 1.28,
    companion: true,
  },
  {
    id: "drink",
    name: "Half-price drink",
    description:
      "Selected item includes a drink at half its price. Demand +18%.",
    factor: 1.18,
    companion: true,
  },
  {
    id: "happy",
    name: "Happy hour",
    description: "Half the orders receive 20% off. Demand +15%.",
    factor: 1.15,
  },
  {
    id: "ad",
    name: "Featured item ad",
    description: "Pay $15 to advertise one item. Demand +30%.",
    factor: 1.3,
    fee: 1500,
  },
];
module.exports = { catalog, promotions };
