'use strict';
function configured(g){return (g.lessonId||'cost-markup-v1')==='cost-markup-v1'&&g.markdownsEnabled===true;}
function enabled(g){return configured(g)&&g.round>=3;}
function current(g,p){return (p.markdowns||[]).find(x=>x.round===g.round)||null;}
function valid(g,p){const x=current(g,p);return !!x&&p.menu.some(m=>m.id===x.id&&m.price===x.regularPrice);}
function setup(g,p,b){const {insist}=require('./game');insist(enabled(g),'Markdown lessons are not enabled.');insist(g.phase==='planning'&&!g.paused&&!p.ready&&p.skippedRound!==g.round,'Markdown decisions are closed.');const item=p.menu.find(x=>x.id===String(b.id));insist(item,'Save a menu item before choosing its markdown.');const rate=Number(b.rate);insist(['number','string'].includes(typeof b.rate)&&String(b.rate).trim()!==''&&Number.isFinite(rate)&&rate>=5&&rate<=75&&Math.abs(rate*100-Math.round(rate*100))<1e-7,'Choose a discount from 5% to 75%, with up to two decimal places.');const discount=Math.floor((item.price*Math.round(rate*100)+5000)/10000);return {round:g.round,id:item.id,rate,regularPrice:item.price,discount,salePrice:item.price-discount};}
function help(g,p,b){const x=setup(g,p,b);p.markdownHelp??=[];if(!p.markdownHelp.includes(g.round))p.markdownHelp.push(g.round);return x;}
function choose(g,p,b){const {money,mathPenalty}=require('./game'),x=setup(g,p,b),correct=money(b.discount)===x.discount&&money(b.salePrice)===x.salePrice,assisted=(p.markdownHelp||[]).includes(g.round);p.markdownChecks??=[];p.markdownChecks.push({...x,correct,assisted});require('./math-progress').record(p,g.round,correct,assisted);p.markdowns??=[];p.markdowns=p.markdowns.filter(v=>v.round!==g.round);p.markdowns.push(x);if(!correct&&!p.wrongRounds.includes(g.round))p.wrongRounds.push(g.round);if(p.roundGuide?.round===g.round)p.roundGuide.review=false;return {...x,correct,roundPenalty:p.wrongRounds.includes(g.round)&&!(p.waivedMathRounds||[]).includes(g.round)?mathPenalty(g):0,message:correct?'Markdown checked and saved for this round.':`Corrected markdown saved: $${(x.discount/100).toFixed(2)} off; sale price $${(x.salePrice/100).toFixed(2)}. You can submit without retrying.`};}
function summary(p,round){const list=p.markdownChecks||[],count=a=>({right:a.filter(x=>x.correct).length,wrong:a.filter(x=>!x.correct).length,assisted:a.filter(x=>x.assisted).length});return {round:count(list.filter(x=>x.round===round)),total:count(list)};}
function offer(g,p,entry){if(!enabled(g))return null;const x=current(g,p),active=valid(g,p)&&x.id===entry.id;const result=require('./lessons/marketing-offers-v1').calculateOffer({...p,promotion:{id:'none'}},{...entry,price:active?x.salePrice:entry.price},require('./lessons').rulesFor(g));return {...result,markdown:active?{...x}:null};}
module.exports={configured,enabled,current,valid,help,choose,summary,offer};
