'use strict';
// Matches Paulie's 13 rewards, 12 mishaps, and 5 duds in catalog order.
module.exports = [
 ['Spatula of Destiny', 'A museum buys Vinnie’s gold-plated spatula. Its exhibit label reads: “Probably dishwasher unsafe.”'],
 ['The Cheese Reserve', 'A fondue convention buys your emergency cheese. Vinnie briefly becomes chairman of the Federal Cheddar Reserve.'],
 ['The Autographed Meatball', 'A collector buys a meatball signed by “Chef Definitely Famous.” Vinnie provides a certificate printed on lasagna.'],
 ['Coupon Singularity', 'The coupons actually scan. Somewhere, a cash register whispers, “The prophecy is fulfilled.”'],
 ['Pickle with a Publicist', 'Your emotional-support pickle lands a sponsorship. It now demands a private dressing room and sparkling brine.'],
 ['Hamster Times Square', 'A hamster billboard goes viral. Tiny commuters line up for your food, accompanied by humans with wallets.'],
 ['Sauce of International Mystery', 'A food festival awards your sauce a prize. The judges describe it as “confusing, but financially compelling.”'],
 ['The Presidential Potato', 'A potato in a tiny suit wins a novelty auction. Its campaign promise: a fryer in every kitchen.'],
 ['Catering for the Secret Society', 'A prepaid catering order arrives for the Secret Society of People Who Like Lunch. Their password is “sandwich.”'],
 ['Ancient Drive-Thru Scroll', 'A collector buys your ancient menu. Archaeologists confirm the combo meal predates the invention of the combo.'],
 ['Forklift of Forks', 'A banquet hall buys Vinnie’s enormous fork collection. He calls it a hostile take-fork. Nobody laughs until he leaves.'],
 ['Chicken Goes Hollywood', 'Your inflatable chicken lands a movie cameo. It thanks the academy, its pump, and “everyone who believed in air.”'],
 ['Apron Treasury', 'An apron contains a forgotten catering payment. Vinnie says the pockets are an offshore account. They are damp.'],
 ['Glitter Gravy Apocalypse', 'The gravy explodes into glitter. A cleanup crew declares your kitchen “festive beyond reasonable doubt.”'],
 ['The Kazoo Philharmonic', 'Three hundred kazoos perform without permission. Pay the return freight before they discover the national anthem.'],
 ['Onions in Group Therapy', 'The onions start a feelings circle. Your staff needs tissues and a substitute vegetable with firmer boundaries.'],
 ['Doughzilla', 'The dough rises, acquires a mailing address, and blocks the cooler. Pay for a larger tub before it runs for mayor.'],
 ['Cart: The Musical', 'Your delivery cart squeaks the entire soundtrack to an imaginary Broadway show. Pay for repairs before opening night.'],
 ['Aprons for Ants', 'Vinnie’s “industrial uniforms” fit ants. Pay the exchange fee while the ants negotiate dental benefits.'],
 ['This Side Existential Crisis', 'Every shipping label says “THIS SIDE MAYBE.” Replace them before the staff begins questioning gravity.'],
 ['Lettuce Night Fever', 'A broken disco rig has convinced the lettuce it is headlining Vegas. Pay for recycling. The cabbage wants a refund.'],
 ['Toaster Exorcism Deluxe', 'The toaster projects “BOO” onto the ceiling. The technician charges extra because the ghost insists on a bagel setting.'],
 ['Mustard World Tour', 'A mustard fountain launches across the kitchen. Pay for cleanup; Vinnie sells the photos as “abstract condiment expressionism.”'],
 ['Receipt Printer Opera', 'The printer sings every receipt in Italian. Pay to repair it before it begins charging customers for an encore.'],
 ['Bubble Wrap Real Estate', 'The packing material occupies three parking spaces and has listed itself as a studio apartment. Pay the disposal fee.'],
 ['Invisible Sandwich Supreme', 'Vinnie upgrades the invisible sandwich with invisible truffle oil. Paulie nods thoughtfully at absolutely nothing. No extra effect.'],
 ['Box: The Extended Universe', 'Inside are seventeen smaller boxes and a trailer for Box 2: Cardboard Reckoning. No extra effect.'],
 ['Witness-Protection Air', 'The box contains air with a fake mustache. Vinnie asks you to call it “Steve.” No extra effect.'],
 ['Duck with Classified Clearance', 'A rubber duck wears sunglasses and shreds a tiny document. It neither confirms nor denies being a duck. No extra effect.'],
 ['Crumb of Unlimited Potential', 'A single crumb sits on a velvet cushion. Its motivational audiobook is just Vinnie yelling “HUSTLE” into a soup can. No extra effect.'],
];
